# Generated by Django 2.1.5 on 2019-02-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_csv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
